name: Semgrep

on:
  pull_request: { }

jobs:
  semgrep:
    name: Finergy Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install and Run Pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Download Semgrep rules
        run: git clone --depth 1 https://github.com/finergyrs/semgrep-rules.git finergy-semgrep-rules

      - name: Download semgrep
        run: pip install semgrep==0.97.0

      - name: Run Semgrep rules
        run: semgrep ci --config ./finergy-semgrep-rules/rules --config r/python.lang.correctness
